services:
  postgres:
    image: postgres:15
    container_name: postgres_db_lab-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    ports:
      - "1616:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

